### ISSUE TITLE
Account Creation not possible on Android Chrome

### ISSUE THREAD

**Issue by MattGibney** [MattGibney/DarkThrone#1]
Registration does not appear to work in the Chrome browser running on Android. There is no visual feedback to the user on what the issue is, it simply seem to be the case that nothing happens.

### Source

> I tried registering on mobile but tapping register did not seem to do anything, also, I received no email address

https://www.reddit.com/r/DarkThroneMMO/comments/1aywhhm/comment/krxya3z/?utm_source=share&utm_medium=web2x&context=3

**Comment by fpopa** [comment]
I just tested this out again, I think the first tap makes the password input field no longer focused, and the second tap on the register button actually works 👀
