### ISSUE TITLE
Banking

### ISSUE THREAD

**Issue by MattGibney** [MattGibney/DarkThrone#4]
A key feature of DarkThrone is the ability to bank gold. Any gold that a player moves to the bank is safe and cannot be stolen by another player, no matter how much they attack.

# Limits
There are limits to banking to help keep the game balanced. These are more-or-less pulled from the original game however and can be changed in the future if required.

## Deposit amount
Players can deposit a maximum of 80% (rounded down) of their current balance into the bank in a single transaction.

## Slots
Players are limited to a maximum of 3 deposits within a 24 hour period. Example:
Player banks at 09:00, 13:00, and 16:00. After this, they are unable to bank again until 09:00 the next day when one of the bank slots opens up again.

# History
Players can see a history of their transactions with details of when and how much they deposited.

**Comment by fpopa** [comment]
can they withdraw 100% in one go?

or are we limiting how many times a player can withdraw in a time window?

**Comment by fpopa** [comment]
Also: when training units / making a purchase:

If the cost for training 10 workers is 10k. The user has 9k cash and 3k banked.
Should we automatically withdraw from the bank or tell the user there's not enough money? 🤔

**Comment by MattGibney** [comment]
Players can withdraw as much as they like as many times as they like even up to 100%.

---

In the original game, it was possible to use banked gold when making purchases, such as training units or upgrading structures. It would use the gold on hand first and then pull the remainder from the bank.

I'm in two minds about this part. While it would do well to replicate the original functionality, I quite like the idea that players expose their gold to a certain amount of risk when making bigger purchases by temporarily exposing themselves to attack and loosing it.

Thoughts?

**Comment by fpopa** [comment]
> I'm in two minds about this part. While it would do well to replicate the original functionality, I quite like the idea that players expose their gold to a certain amount of risk when making bigger purchases by temporarily exposing themselves to attack and loosing it.

yep, that's the exact thought I was thinking about as well.

As long as we prevent people from creating bots, I think we should go with this, otherwise, it will be very very punishing.

example:
I need five millions, but each time I get to three millions a bot detects that and automatically attacks me making me lose it again and again.

**Comment by fpopa** [comment]
Just noticed this is `in progress`, have you already started working on it or is it up for grabs?
